### ISSUE TITLE
Depotdir larger than cache?

### ISSUE THREAD

**Issue by fredrikbaberg** [devedse/DeveLanCacheUI_Backend#59]
Hi,
I've had Lancache with DeveLanCacheUI running for several weeks, as I wanted a UI to see what was going on.
Today I noticed `/var/develancacheuidata` takes more space than the cache itself. Is this intended behavior?
Should there be some maintenance of the `.csv` files?

`develancacheui` contains the folder `backend/depotdir/processed` with a lot of `.csv` files.
![image](https://github.com/user-attachments/assets/8fca1a1a-6a18-4880-abb5-aae331e23004)

My `docker-compose.yml` file is as follows:
```
x-restart-policy: &restart-policy "unless-stopped"
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: *restart-policy
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: *restart-policy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs

  develancacheui_backend:
    image: devedse/develancacheui_backend:latest
    restart: unless-stopped
    ports:
      - '7301:80'
    environment:
      - TZ=Europe/Stockholm
      - LANG=en_GB.UTF-8
    volumes:
      - ${CACHE_ROOT}/develancacheui/backend:/var/develancacheuidata
      - ${CACHE_ROOT}/logs:/var/develancacheui/lancachelogs:ro
    dns:
      - ${UPSTREAM_DNS}
  develancacheui_frontend:
    image: devedse/develancacheui_frontend:latest
    restart: unless-stopped
    ports:
      - '7302:80'
    environment:
      - BACKENDURL=https://<Redacted URL>/backend #iclude http/https here
      #- AllowedHosts=*
```
with `.env`:
```
lancache:~/lancache# cat .env 
## See the "Settings" section in README.md for more details

## Set this to true if you're using a load balancer, or set it to false if you're using separate IPs for each service.
## If you're using monolithic (the default), leave this set to true
USE_GENERIC_CACHE=true

## IP addresses that the lancache monolithic instance is reachable on
## Specify one or more IPs, space separated - these will be used when resolving DNS hostnames through lancachenet-dns. Multiple IPs can improve cache priming performance for some services (e.g. Steam)
## Note: This setting only affects DNS, monolithic and sniproxy will still bind to all IPs by default
LANCACHE_IP=<Redacted IP>

## IP address on the host that the DNS server should bind to
DNS_BIND_IP=<Redacted IP>

## DNS Resolution for forwarded DNS lookups
UPSTREAM_DNS=<Redacted IP>

## Storage path for the cached data
## Note that by default, this will be a folder relative to the docker-compose.yml file
CACHE_ROOT=./lancache

## Change this to customise the maximum size of the disk cache (default 2000g).
## If you have more storage, you'll likely want to increase this.
## The cache server will prune content on a least-recently-used basis if it
## starts approaching this limit.
CACHE_DISK_SIZE=6g

## Sets the minimum free disk space that must be kept at all times.
## When the available free space drops below the set amount for any reason,
## the cache server will begin pruning content to free up space.
## Prevents accidentally running out of disk space if CACHE_DISK_SIZE is set too high.
MIN_FREE_DISK=500m

## Change this to allow sufficient index memory for the nginx cache manager (default 500m)
## We recommend 250m of index memory per 1TB of CACHE_DISK_SIZE
CACHE_INDEX_SIZE=500m

## Change this to limit the maximum age of cached content (default 3650d)
CACHE_MAX_AGE=3650d

## Set the timezone for the docker containers, useful for correct timestamps on logs (default Europe/London)
## Formatted as tz database names. Example: Europe/Oslo or America/Los_Angeles
TZ=Europe/Stockholm
```
