### ISSUE TITLE
Time Offset Issue Between Logs Timestamps and Web UI

### ISSUE THREAD

**Issue by irmandos** [devedse/DeveLanCacheUI_Backend#74]
I am experiencing a 2-hour time offset between the timestamps displayed in the DeveLanCacheUI web interface and the actual timestamps in my LanCache logs. While the logs show the correct local time (15:xx), the web UI displays the time as 13:xx.

### Steps Taken:
1. Map the timezone and local time into Docker containers for both LanCache and DeveLanCacheUI (both frontend and backend) using the following docker-compose snippet:
```
environment:
  - TZ=Africa/Johannesburg
  - LANG=en_GB.UTF-8
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/timezone:/etc/timezone:ro
```
2. View the timestamps in the LanCache logs (confirming they are correct).
3. Compare the timestamps in the DeveLanCacheUI web interface.

### Expected Behavior:
The timestamps in the web UI should match the local time (as seen in the logs).

### Observed Behavior:
There is a 2-hour offset in the web UI, where the time displayed is 2 hours earlier than the correct local time.

### Additional Information:
Docker is configured with the TZ environment variable set to Africa/Johannesburg, which reflects my local time zone.
LanCache logs show the correct time, confirming that the timezone configuration is working correctly within the container.
Screenshot comparing log timestamps with the web UI is attached for reference.
![Image](https://github.com/user-attachments/assets/03d754ef-91ca-4863-ba9a-4fa00606a439)

### Environment Details:
OS: Truenas Community Edition 25.04 (Scale) 
Docker version: Docker version 27.5.0, build a187fa5
DeveLanCacheUI_Backend version: 
- Frontend Version: 1.0.73.0
- Backend Version: 1.0.192.0
- Steam Change Number: 29105364

### Logs and Configurations:
Please let me know if additional logs or configuration details are needed.

**Comment by irmandos** [comment]
Hello @devedse, thank you for your response, I hope the below will assist.
It does seem to be a backend issue when looking at the dozzle logs timestamps.

![Image](https://github.com/user-attachments/assets/717ed3e4-b435-4980-994f-19e71c03487a)

![Image](https://github.com/user-attachments/assets/ed02b1da-3790-4421-b5da-00fe6f1197fc)

![Image](https://github.com/user-attachments/assets/ae096707-6027-4afc-9e35-6c2c0e8c47f6)

docker-compose.yml:

```
services:
  develancacheui_backend:
    dns:
      - 1.1.1.2
    environment:
      - LanCacheLogsDirectory=/var/develancacheui/lancachelogs
      - DeveLanCacheUIDataDirectory=/var/develancacheuidata
      - >-
        ConnectionStrings__DefaultConnection=Data
        Source={DeveLanCacheUIDataDirectory}/database/develancacheui.db;
      - TZ=Africa/Johannesburg
      - LANG=en_GB.UTF-8
      - Feature_DirectSteamIntegration=true
      - Feature_SkipLinesBasedOnBytesRead=true
      - AllowedHosts=*
    image: devedse/develancacheui_backend:latest
    ports:
      - 192.168.69.12:7301:80
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/nvme512/Apps_Config/lancache/develancacheui:/var/develancacheuidata
      - >-
        /mnt/nvme512/Apps_Config/lancache/logs:/var/develancacheui/lancachelogs:ro
  develancacheui_frontend:
    environment:
      - BACKENDURL=http://192.168.69.12:7301
      - AllowedHosts=*
      - TZ=Africa/Johannesburg
    image: devedse/develancacheui_frontend:latest
    ports:
      - 192.168.69.12:7302:80
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```
